function plot_index_finger_exo_2d(p,estimates,rj)

% geometric parameters
% lengths
x_a = p(1); % m
y_a = p(2); % m
l_bc = p(3); % m
l_cd = p(4); % m
l_ah = p(5);
l_ce = p(6);
l_ef = p(7);
l_fg = p(8);
l_gh = p(9);
l_fg = p(8);
l_gk = p(10);
l_fi = p(11);
l_ij = p(12);
l_kj = 0.01;

joint_radius = 0.005;

% angle estimates
exo_t1 = estimates(1);
exo_t2 = estimates(2);
exo_x3 = estimates(3);
t_mcp = estimates(4);
exo_t5 = estimates(5);
exo_t6 = estimates(6);
exo_t7 = estimates(7);
t_pip = estimates(8);
exo_t9 = estimates(9);
exo_t10 = estimates(10);
exo_x11 = estimates(11);
t_dip = estimates(12);

% evaluating model parameters
% pip chain
l_hf = sqrt(l_gh*l_gh+l_fg*l_fg);
t_hfg = atan(l_gh/l_fg);
l_dh = l_ah-exo_x3;
l_ch = sqrt(l_cd*l_cd+l_dh*l_dh);
t_hfg = atan(l_gh/l_fg);
t_dch = atan(l_dh/l_cd);

% plotting mcp chain
plot(-[0 real(l_bc*exp(i*exo_t1)),...
    real(l_bc*exp(i*exo_t1)+l_cd*exp(i*exo_t2)),...
    real(l_bc*exp(i*exo_t1)+l_cd*exp(i*exo_t2)+exo_x3*exp(i*(t_mcp-pi)))],...
    [0 imag(l_bc*exp(i*exo_t1)),...
    imag(l_bc*exp(i*exo_t1)+l_cd*exp(i*exo_t2)),...
    imag(l_bc*exp(i*exo_t1)+l_cd*exp(i*exo_t2)+exo_x3*exp(i*(t_mcp-pi)))],...
    'linewidth',4);
hold on;
plot(-[real(l_bc*exp(i*exo_t1)+l_cd*exp(i*exo_t2)),...
    real(l_bc*exp(i*exo_t1)+l_cd*exp(i*exo_t2)+exo_x3*exp(i*(t_mcp-pi)))],...
    [imag(l_bc*exp(i*exo_t1)+l_cd*exp(i*exo_t2)),...
    imag(l_bc*exp(i*exo_t1)+l_cd*exp(i*exo_t2)+exo_x3*exp(i*(t_mcp-pi)))],...
    '-m','linewidth',4);

rectangle('position',[-(real(l_bc*exp(i*exo_t1)+l_cd*exp(i*exo_t2)+exo_x3*exp(i*(t_mcp-pi))))-joint_radius/2,...
    imag(l_bc*exp(i*exo_t1)+l_cd*exp(i*exo_t2)+exo_x3*exp(i*(t_mcp-pi)))-joint_radius/2,joint_radius,joint_radius],...
    'curvature',[1,1],'linewidth',2,'linestyle','-','facecolor','r');

rectangle('position',[0-rj/2,0-rj/2,rj,rj],...
    'curvature',[1,1],'linewidth',2,'linestyle','-','facecolor','b');


 % plotting pip chain
 plot(-[l_bc*cos(exo_t1),...
     l_bc*cos(exo_t1)+l_ce*cos(exo_t5),...
     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6),...
     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+l_fg*cos(exo_t7),...
     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+l_fg*cos(exo_t7)-...
     l_gh*cos(t_pip),...
     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+...
     l_fg*cos(exo_t7)-l_gh*cos(t_pip)-(l_ah-exo_x3)*cos(t_mcp)],...
     [l_bc*sin(exo_t1),...
     l_bc*sin(exo_t1)+l_ce*sin(exo_t5),...
     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6),...
     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fg*sin(exo_t7),...
     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fg*sin(exo_t7)-...
     l_gh*sin(t_pip),...
     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+...
     l_fg*sin(exo_t7)-l_gh*sin(t_pip)-(l_ah-exo_x3)*sin(t_mcp)],...
    'linewidth',4);
 
 % plotting dip chain
 plot(-[l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+l_fg*cos(exo_t7),...
     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+l_fg*cos(exo_t7)+...
     l_gk*cos(t_pip),...
     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+l_fg*cos(exo_t7)+...
     l_gk*cos(t_pip)+l_kj*cos(t_dip)],...
     [l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fg*sin(exo_t7),...
     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fg*sin(exo_t7)+...
     l_gk*sin(t_pip),...
     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fg*sin(exo_t7)+...
     l_gk*sin(t_pip)+l_kj*sin(t_dip)],...
    'linewidth',4);

rectangle('position',[-(l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+l_fg*cos(exo_t7)-l_gh*cos(t_pip))-joint_radius/2,...
    l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fg*sin(exo_t7)-l_gh*sin(t_pip)-joint_radius/2,joint_radius,joint_radius],...
    'curvature',[1,1],'linewidth',2,'linestyle','-','facecolor','r');

rectangle('position',[-(l_bc*cos(exo_t1)+l_ce*cos(exo_t5))-rj/2,...
    l_bc*sin(exo_t1)+l_ce*sin(exo_t5)-rj/2,rj,rj],...
    'curvature',[1,1],'linewidth',2,'linestyle','-','facecolor','b');

rectangle('position',[-(l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+...
    l_ef*cos(exo_t6)+l_fg*cos(exo_t7)+...
     l_gk*cos(t_pip))-joint_radius/2,...
    l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fg*sin(exo_t7)+...
     l_gk*sin(t_pip)-joint_radius/2,joint_radius,joint_radius],...
    'curvature',[1,1],'linewidth',2,'linestyle','-','facecolor','r');

% full exo plotting
% % plotting pip chain
% plot(-[l_bc*cos(exo_t1),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+l_fg*cos(exo_t7),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+l_fg*cos(exo_t7)-l_gh*cos(t_pip),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+...
%     l_fg*cos(exo_t7)-l_gh*cos(t_pip)-(l_ah-exo_x3)*cos(t_mcp)],...
%     [l_bc*sin(exo_t1),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fg*sin(exo_t7),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fg*sin(exo_t7)-l_gh*sin(t_pip),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+...
%     l_fg*sin(exo_t7)-l_gh*sin(t_pip)-(l_ah-exo_x3)*sin(t_mcp)],...
%     'linewidth',4);
% 
% plot(-[l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+l_fg*cos(exo_t7),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+l_fg*cos(exo_t7)-l_gh*cos(t_pip),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+...
%     l_fg*cos(exo_t7)-l_gh*cos(t_pip)-(l_ah-exo_x3)*cos(t_mcp)],...
%     [l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fg*sin(exo_t7),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fg*sin(exo_t7)-l_gh*sin(t_pip),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+...
%     l_fg*sin(exo_t7)-l_gh*sin(t_pip)-(l_ah-exo_x3)*sin(t_mcp)],...
%     '-m','linewidth',4);

% % plotting dip chain
% plot(-[l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+l_fi*cos(exo_t9),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+...
%     l_fi*cos(exo_t9)+l_ij*cos(exo_t10),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+...
%     l_fi*cos(exo_t9)+l_ij*cos(exo_t10)-exo_x11*cos(t_dip),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+...
%     l_fi*cos(exo_t9)+l_ij*cos(exo_t10)-exo_x11*cos(t_dip)-l_gk*cos(t_pip),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+...
%     l_fi*cos(exo_t9)+l_ij*cos(exo_t10)-exo_x11*cos(t_dip)-l_gk*cos(t_pip)-...
%     l_fg*cos(exo_t7)],...
%     [l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+l_fi*sin(exo_t9),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+...
%     l_fi*sin(exo_t9)+l_ij*sin(exo_t10),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+...
%     l_fi*sin(exo_t9)+l_ij*sin(exo_t10)-exo_x11*sin(t_dip),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+...
%     l_fi*sin(exo_t9)+l_ij*sin(exo_t10)-exo_x11*sin(t_dip)-l_gk*sin(t_pip),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+...
%     l_fi*sin(exo_t9)+l_ij*sin(exo_t10)-exo_x11*sin(t_dip)-l_gk*sin(t_pip)-...
%     l_fg*sin(exo_t7)],...
%     'linewidth',4);
% 
% plot(-[l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+...
%     l_fi*cos(exo_t9)+l_ij*cos(exo_t10),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+...
%     l_fi*cos(exo_t9)+l_ij*cos(exo_t10)-exo_x11*cos(t_dip),...
%     l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+...
%     l_fi*cos(exo_t9)+l_ij*cos(exo_t10)-exo_x11*cos(t_dip)-l_gk*cos(t_pip)],...
%     [l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+...
%     l_fi*sin(exo_t9)+l_ij*sin(exo_t10),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+...
%     l_fi*sin(exo_t9)+l_ij*sin(exo_t10)-exo_x11*sin(t_dip),...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+...
%     l_fi*sin(exo_t9)+l_ij*sin(exo_t10)-exo_x11*sin(t_dip)-l_gk*sin(t_pip)],...
%     '-m','linewidth',4);

% rectangle('position',[-(l_bc*cos(exo_t1)+l_ce*cos(exo_t5)+l_ef*cos(exo_t6)+...
%     l_fi*cos(exo_t9)+l_ij*cos(exo_t10)-exo_x11*cos(t_dip))-joint_radius/2,...
%     l_bc*sin(exo_t1)+l_ce*sin(exo_t5)+l_ef*sin(exo_t6)+...
%     l_fi*sin(exo_t9)+l_ij*sin(exo_t10)-exo_x11*sin(t_dip)-joint_radius/2,joint_radius,joint_radius],...
%     'curvature',[1,1],'linewidth',2,'linestyle','-','facecolor','r');

axis([-0.14 0.07 -0.12 0.085]);
